// <auto-generated />
namespace Nestor.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update1_NestsUpdatesIdSequence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update1_NestsUpdatesIdSequence));
        
        string IMigrationMetadata.Id
        {
            get { return "201806181927120_Update1_NestsUpdatesIdSequence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
